attack:
    epsilon: 16
    steps: 100
    input_size: 512
    mode: sds
    img_path: /data/home/yekai/github/DiffAdvPerturbationBench/datasets/VGGFace2-clean/0/set_B
    output_path: out_vk/
    alpha: 1
    g_mode: "-"
    use_wandb: False
    project_name: iclr_mist
    diff_pgd: [False, 0.2, 'ddim100'] # un-used feature
    using_target: False
    target_rate: 5
    device: 0
    max_exp_num: 100
